#@ load("@ytt:overlay", "overlay")

#! Matching by Deployment is acceptable because we have only one Deployment :-)
#@overlay/match by=overlay.subset({"kind": "Deployment"})
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by=overlay.map_key("name")
        - name: manager
          imagePullPolicy: Never
